name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.21
          apps: sbt
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run tests
        run: sbt test
      - run: npm run build4gh

      - name: Setup Pages
        if: github.ref_type == 'tag'
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        if: github.ref_type == 'tag'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    name: Deploy to github pages
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v2