name: Check format

on:
  workflow_call:

jobs:

  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.21
          apps: sbt
      - name: Check format (scalafmt)
        shell: bash
        run: sbt scalafmtCheckAll
      - name: Check format (scalafix)
        shell: bash
        run: sbt "scalafix --check"
